title = "Hidden Jewels Travel"
baseURL = "https://hiddenjewelstravel.com/"
theme = "ananke"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
mainSections = ["none"]
text_color = "grey"
author = "Julie" # default author, override via `author` in a posts front matter
favicon = ""
site_logo = "images/hjt4.svg"
TIMEZONE = "America/Denver"
description = "Your favorite travel planner"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-blue"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-dark-blue-60"
recent_posts_number = 3
body_classes = "avenir bg-lightest-blue"

[params.ananke.social.share]
networks = [
  "email",
  "facebook"
]

[params.ananke.social.follow]
networks = [
  "facebook",
  "instagram"
]

[params.ananke.social.facebook]
username = "hiddenjewelstravel"
# profilelink = "https://www.facebook.com/hiddenjewelstravel"

[params.ananke.social.instagram]
username = "hiddenjewelstravel" # Replace with your Instagram username

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 20

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 40


